<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Akshay" failures="1" tests="2" name="stepDefinations.TestRunner" time="33.896" errors="0" timestamp="2024-12-21T23:02:35 IST" skipped="0">
  <testcase classname="stepDefinations.TestRunner" name="runScenario" time="18.107">
    <failure message="Account Not created expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Account Not created expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertTrue(Assert.java:57)
at stepDefinations.CreateNewAccountSteps.user_should_see_a_message_account_created_successfully(CreateNewAccountSteps.java:56)
at âœ½.user should see a message account created successfully(file:///D:/Learning/New%20Workspace/BDDAssignment/src/test/resources/Features/CreateNewAccount.feature:9)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="stepDefinations.TestRunner" name="runScenario" time="15.789"/>
</testsuite> <!-- stepDefinations.TestRunner -->
